print("hello world from python!")
print("i am working on python")
print("i am learning python")
print("python is a great language")
print("write something in python")
print("python is easy to learn")
print("python is a popular language")
print("python is used for web development")
print("bir araba var kaç tekeri var")
